apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  type: LoadBalancer
  ports:
    - name: vault
      port: 80
      targetPort: 8200
      protocol: TCP
  selector:
    app: vault
